# Send this build to the travis.ci container-based infrastructure
# which typically has more capacity than the open-source Linux pool
sudo: false
language: python
python:
  - "2.7"
services:
  - redis-server
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
# command to run tests
script: coverage run --source=app.py app_tests.py
after_success: coveralls
